export type BlockerCategory =
  | "PROBLEM_MODELING"
  | "PATTERN_RECOGNITION"
  | "ALGORITHM_SELECTION"
  | "INVARIANT_REASONING"
  | "STATE_DESIGN"
  | "COMPLEXITY_OPTIMIZATION"
  | "IMPLEMENTATION"
  | "EDGE_CASES"
  | "DEBUGGING"
  | "LANGUAGE_KNOWLEDGE";
