"use client";

import { useRef, useState } from "react";

const copies = {
  en: { eyebrow: "DATA PORTABILITY", title: "Export and restore", lede: "Your local data stays portable. Create a full backup, a spreadsheet summary, readable notes, or an AI-ready dataset.", filters: "Filters", from: "From", to: "To", status: "Status", problem: "Problem slug", include: "Include", metadata: "Problem metadata", submissions: "Submissions", code: "Source code", analysis: "AI analysis", reviews: "Review history", json: "Full JSON backup", jsonNote: "Keep metadata, submissions, and code selected for a restorable backup; select reviews for a complete learning-state archive.", csv: "CSV summary", md: "Markdown history", ai: "AI Dataset (JSONL)", restore: "Restore JSON backup", restoreNote: "Restoring is idempotent: existing sessions and submissions are updated instead of duplicated.", choose: "Choose backup file", restoring: "Restoring…" },
  zh: { eyebrow: "数据可迁移", title: "导出与恢复", lede: "本地数据始终可带走。你可以生成完整备份、表格摘要、可读笔记，或供 AI 使用的数据集。", filters: "筛选条件", from: "开始日期", to: "结束日期", status: "状态", problem: "题目 slug", include: "包含内容", metadata: "题目元数据", submissions: "提交记录", code: "源代码", analysis: "AI 分析", reviews: "复习记录", json: "完整 JSON 备份", jsonNote: "可恢复备份需勾选题目、提交和代码；再勾选复习记录即可完整保存学习状态。", csv: "CSV 摘要", md: "Markdown 历史", ai: "AI 数据集（JSONL）", restore: "恢复 JSON 备份", restoreNote: "恢复操作是幂等的：已有场次和提交会更新，不会产生重复数据。", choose: "选择备份文件", restoring: "恢复中…" },
} as const;

export function DataManager({ locale }: { locale: "en" | "zh" }) {
  const copy = copies[locale]; const fileRef = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [filters, setFilters] = useState({ from: "", to: "", status: "ALL", problem: "", metadata: true, submissions: true, code: true, analysis: true, reviews: false });
  function set<K extends keyof typeof filters>(key: K, value: (typeof filters)[K]) { setFilters((current) => ({ ...current, [key]: value })); }
  function exportUrl(format: string) { const query = new URLSearchParams({ format, from: filters.from, to: filters.to, status: filters.status, problem: filters.problem, metadata: String(filters.metadata), submissions: String(filters.submissions), code: String(filters.code), analysis: String(filters.analysis), reviews: String(filters.reviews) }); return `/api/export?${query}`; }
  async function restore(file: File) { setBusy(true); setMessage(""); try { const payload = JSON.parse(await file.text()); const response = await fetch("/api/import/backup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { restored?: Record<string, number>; error?: string }; if (!response.ok) throw new Error(body.error || "Restore failed"); setMessage(locale === "zh" ? `恢复完成：${body.restored?.sessions ?? 0} 个场次，${body.restored?.attempts ?? 0} 次提交。` : `Restore complete: ${body.restored?.sessions ?? 0} sessions and ${body.restored?.attempts ?? 0} attempts.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Restore failed"); } finally { setBusy(false); if (fileRef.current) fileRef.current.value = ""; } }
  const formats = [{ key: "json", title: copy.json, note: copy.jsonNote }, { key: "csv", title: copy.csv, note: locale === "zh" ? "适合在 Excel / Numbers 中筛选统计。" : "Best for filtering and analysis in a spreadsheet." }, { key: "markdown", title: copy.md, note: locale === "zh" ? "适合阅读、归档或粘贴到笔记应用。" : "Readable archive for notes and documentation." }, { key: "ai", title: copy.ai, note: locale === "zh" ? "每行一个输入/输出样本，保留数据完整度警告。" : "One input/output sample per line with completeness warnings." }];
  return <main className="shell data-page"><header className="data-hero"><div><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p className="lede">{copy.lede}</p></div></header>
    <div className="data-layout"><aside className="filter-card"><p className="eyebrow">{copy.filters}</p><label>{copy.from}<input type="date" value={filters.from} onChange={(event) => set("from", event.target.value)} /></label><label>{copy.to}<input type="date" value={filters.to} onChange={(event) => set("to", event.target.value)} /></label><label>{copy.status}<select value={filters.status} onChange={(event) => set("status", event.target.value)}><option value="ALL">{locale === "zh" ? "全部" : "All"}</option><option value="SOLVED">{locale === "zh" ? "已通过" : "Solved"}</option><option value="ACTIVE">{locale === "zh" ? "进行中" : "Active"}</option><option value="ABANDONED">{locale === "zh" ? "未完成" : "Abandoned"}</option></select></label><label>{copy.problem}<input value={filters.problem} onChange={(event) => set("problem", event.target.value)} placeholder="two-sum" /></label><p className="eyebrow include-heading">{copy.include}</p>{(["metadata", "submissions", "code", "analysis", "reviews"] as const).map((key) => <label className="check-row" key={key}><input type="checkbox" checked={filters[key]} onChange={(event) => set(key, event.target.checked)} />{copy[key]}</label>)}</aside>
      <section><div className="export-grid">{formats.map((format) => <article className="export-card" key={format.key}><span>{format.key === "json" ? "{}" : format.key === "csv" ? "▦" : format.key === "markdown" ? "M↓" : "AI"}</span><h2>{format.title}</h2><p>{format.note}</p><a className="manual-primary" href={exportUrl(format.key)}>{locale === "zh" ? "下载" : "Download"} →</a></article>)}</div>
        <article className="restore-card"><div><p className="eyebrow">RESTORE</p><h2>{copy.restore}</h2><p>{copy.restoreNote}</p></div><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void restore(file); }} /><button className="manual-primary" disabled={busy} onClick={() => fileRef.current?.click()}>{busy ? copy.restoring : copy.choose}</button></article>{message && <p className={message.toLowerCase().includes("fail") || message.includes("不") || message.includes("missing") ? "error-banner" : "success-banner"}>{message}</p>}
      </section></div>
  </main>;
}
